### ISSUE TITLE
Skyhook Poles placed in complete edge/corder of an foundation prevent other foundation placements

### ISSUE THREAD

**Issue by Fireztonez** [DavidHGillen/Satisfactory_AB-CableChoices#1]
This is not the end of the world, but a little issue I found with the Skyhook Poles, when you placed on the complete edge or corner of an foundation, this prevent other foundation to be placed on that side due to "Encroaching Clearance". This doesn't append with Vanilla Pole. I'm not sure what you can do to fixed that, but if you find a way, this will be nice!

**Cable Choices + version:** 0.0.1
**Satisfactory Build:** 150216
**SML version:** 3.0.0

**Comment by DavidHGillen** [comment]
Noted, I will diagnose this and try and get it solved for next release

**Comment by DavidHGillen** [comment]
I believe I fixed this and have received no further reports.
