### ISSUE TITLE
Feature Request: Transmission Wire Termination/Transmission Wire to Regular Power Wire Adapter

### ISSUE THREAD

**Issue by jayzosayers** [DavidHGillen/Satisfactory_AB-CableChoices#13]
Then vanilla power towers don't terminate in a particularly realistic way. As convenient as the tap points underneath the tower are, I don't like them. I've been using the ground spikes that are already in the mod to make a more realistic-looking termination, but at present, they only take either a single transmission wire connection OR a single power line connection (in the case of the regular ground spike).

I'm proposing a variant of the ground spike that acts like a wall/ceiling/beam connector that allows you to connect regular powerlines to a transmission line. This would behave exactly like a regular power tower except it would have two tap points and they'd be on top of the transmission line connection making it appear as if the power lines come down from the tall towers and into the regular system.

![Satisfactory   18_10_2024 21_49_10](https://github.com/user-attachments/assets/801fcd94-7a40-448b-b2e2-626bfb5b5cbb)
 I've included a screenshot as an example of what this could look like. I've attached the transmission lines to a ground spike and connected the outer two regular power lines to a wall/ceiling/beam power connector that sits on top of the ground spike mesh so that they appear connected but are non-functional. A beam/wall/ceiling mountable connection would allow for flexibility in the positioning of the adapter piece but could quite easily just be two power pole models.

Thanks for the awesome mod. This and the Fluid Extras mods are in my "must-have" mods.

(Edits: Further clarifications)

**Comment by DavidHGillen** [comment]
Been thinking of something along these lines after a few different requests. will think on it. stay tuned

**Comment by DavidHGillen** [comment]
The new Wall mounted power tower connectors should help you build stuff like this more easily. I'm open to further suggestions but I'll close this for now as I think the latest should help with what you want.
