### ISSUE TITLE
Crash with 1.0.5

### ISSUE THREAD

**Issue by N-Montana** [DavidHGillen/Satisfactory_AB-CableChoices#15]
I'm assuming you're aware of the last update making the mod incompatible and crashing on launch. But wanted to make sure an issue was open since my current save relies heavily on this mod.

Reading the patch notes I know there was some change to power poles clearance so understand if it's more work to update.

**Comment by DavidHGillen** [comment]
Latest build should fix issues, let me know if there's further problems.

**Comment by N-Montana** [comment]
Looks to be working well, thank you!
