### ISSUE TITLE
Powerlines going off to infinity

### ISSUE THREAD

**Issue by azariah001** [DavidHGillen/Satisfactory_AB-CableChoices#4]
Hello, My friend and I recently started using this mod and ran into a few issue with the Paintable Power Line in particular and... the behaviour for the multiplayer guest is... random. Got a few screenshots.

Guest ( GTX 1060 1440p )
![image](https://user-images.githubusercontent.com/5634872/122639760-10cdce00-d13f-11eb-835e-5dbab73f01f6.png)

Host ( GTX 3080 4k )
![image](https://user-images.githubusercontent.com/5634872/122639778-22af7100-d13f-11eb-945e-3c74ed9c0a13.png)

Also Guest
![image](https://user-images.githubusercontent.com/5634872/122639837-889bf880-d13f-11eb-9556-9daac6c6b664.png)

Source of the last images cables..... our power distribution station.

Host
![image](https://user-images.githubusercontent.com/5634872/122639913-f9431500-d13f-11eb-889e-698c3106888b.png)

Guest
![image](https://user-images.githubusercontent.com/5634872/122639919-04964080-d140-11eb-9e64-6209fff22917.png)

Note that all of the random cables are selectable by the guest as if they are actually there, ie, not just visual, and the cables are destructible and the host sees the cable removed from its actual location. My guess as a software dev is that the origin of the cables is being sent to the guest but not the other end and thus the coordinate is defaulting to "0".

Weirdly this doesn't exist for new cables, but only for cables loaded off of the save file, only for the guest, and only for Power Pole to Power Pole. Wall Power to Power Pole works just fine.

If you'd like a copy of the save file I can send that through.

**Comment by DavidHGillen** [comment]
When placing a powerline I'm using the blueprint system to lookup the connections and place my spline between them. The BP functions I have access to aren't exactly reliable https://www.youtube.com/watch?v=Svqw-rw9l-4 I thought I'd prevented it from doing this, but apparently there's some client side ones I missed.

For a variety of reasons I'll probably be moving the spline generation and the position lookup to C++, which will be the next thing I try to do after I'm finished adding C++ to my Packing machine in my other mod. So hold tight till then and apologies for the inconvience.

**Comment by mikeloeven** [comment]
This issue appears to be caused when a mod is removed and the connected machine is deleted on save load. The cable will remain and render as a max length cable going off into the distance. These can be deconstructed without causing issues although it would be nice for the cables to run some checks and self delete if they cannot find the item they were previously connected to

**Comment by DavidHGillen** [comment]
Fixed with base game changes in U8
