### ISSUE TITLE
Crashes when launching with Ficsit networks

### ISSUE THREAD

**Issue by gammeflamme** [DavidHGillen/Satisfactory_AB-CableChoices#5]
The cristmas patch patch for _Ficsit networks_ doesn't work with _Cable Choices +_.
Crashes on launch.
_Ficsits networks_ creator beleves it is caused by _Cable Choices +_ because previously _Cable Choices +_ had broken unused blueprints that _Ficsits networks_ still tried to ananlyze/load.

`Version: 174506, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: -, IsUsingMods: Yes
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000
FactoryGame_CoreUObject_Win64_Shipping!UScriptStruct::TCppStructOps<FRotator>::Identical() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\public\uobject\class.h:1341]
FactoryGame_Engine_Win64_Shipping!UBlueprintGeneratedClass::BuildCustomPropertyListForPostConstruction() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:449]
FactoryGame_Engine_Win64_Shipping!UBlueprintGeneratedClass::UpdateCustomPropertyListForPostConstruction() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:628]
FactoryGame_Engine_Win64_Shipping!UBlueprintGeneratedClass::SerializeDefaultObject() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:298]
FactoryGame_CoreUObject_Win64_Shipping!UClass::SerializeDefaultObject() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\public\uobject\class.h:3103]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::EventDrivenSerializeExport() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3193]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::ProcessImportsAndExports_Event() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3523]
FactoryGame_CoreUObject_Win64_Shipping!<lambda_021cf6e1d064bc3759a30032930b9dad>::operator()() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:2291]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::ProcessAsyncLoading() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4055]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::TickAsyncThread() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4840]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4767]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]
`
[FactoryGame.log](https://github.com/DavidHGillen/Satisfactory_AB-CableChoices/files/7636172/FactoryGame.log)

**Comment by DavidHGillen** [comment]
Noted. I will leave this open till I push a fix.

**Comment by DavidHGillen** [comment]
This should be fixed by 0.3.2, if isn't reopen this and post the crash log thanks.
