### ISSUE TITLE
Cable Choices + Ficsmas Lights

### ISSUE THREAD

**Issue by Zaphodjoe** [DavidHGillen/Satisfactory_AB-CableChoices#8]
The Ficsmas Power Line alternate calls for an item that isn't in the game. I can build the line with no cost on from Pak but then when you deconstruct it, the item is in a loot crate that you  can't loot. You have to delete it. If I look in recipes, it comes up as an alt recipe for that item but can't be created or even made with pak utility.

**Comment by DavidHGillen** [comment]
This seems to be a cross compatibility issue with sorting the unsortable. I will close this when I try a couple things to solve it on my end.
